# Generated by Django 4.2.4 on 2023-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemixer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='alphabetic_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
