# Generated by Django 4.2.4 on 2023-08-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemixer', '0003_remove_movie_genre_remove_movie_length_in_minutes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailerLink',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='userRating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
