# Generated by Django 4.2.4 on 2023-08-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemixer', '0004_delete_genre_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_created',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
